In [2]:
import numpy as np

A = np.array([[0, 1], [2, 3], [4, 5]])
A


array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
x = np.dot(A, B)
x

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [9]:
x.max()


47